### ISSUE TITLE
Implement Promotion Service

### ISSUE THREAD

**Issue by tapas4java** [anitechcs/microservices-reference-application#40]
- Promotion service implementation
- DB schema design
- Containerize the deployment

**Comment by tapas4java** [comment]
@chanduthedev I believe this one completed already. Can we close it or anything pending on this?

**Comment by chanduthedev** [comment]
@tapas4java Need to update list size from 5 to 10 as per your review comments. I will close this issue after incorporating review comments.

**Comment by chanduthedev** [comment]
Review comments implemented in issue #70 and changes merged to master branch.
